@startuml

title SuihankiDB ER
skinparam linetype ortho

' single entities
entity "author" as a {
    author_id
    --
    author_name
}
entity "book" as b {
    book_id
    --
    book_name
    --
    main_author_id
    --
    circle_id
    --
    publish_date
    --
    note
}
entity "circle" as c {
    circle_id
    --
    circle_name
    --
    book_id
}
entity "page" as p {
    page_id
    --
    book_id
    --
    page_number
    --
    image_path
}
entity "tag" as t {
    tag_id
    --
    tag_name
}

' intermediate entities
entity "author_books" as ab {
    author_books_id
    --
    author_id
    --
    book_id
}
entity "author_circles" as ac {
    author_circles_id
    --
    author_id
    --
    circle_id
}
entity "book_tags" as bt {
    book_tags_id
    --
    book_id
    --
    tag_id
}

' author contains
a ||--|{ ab
a ||--|{ ac

' book contains
b ||--|{ ab
b ||--|{ p
b ||--o{ bt

' circle contains
c ||--|{ b
c ||--|{ ac

' tag contains
t ||--o{ bt

@enduml