@startuml

title SuihankiDB ER
skinparam linetype ortho

entity "book" as b {
    book_id
    --
    book_name
    --
    publisher
    --
    publish_date
    --
    note
}
entity "author_books" as ab {
    author_books_id
    --
    author_id
    --
    book_id
}
entity "author" as a {
    author_id
    --
    author_name
}
entity "page" as p {
    page_id
    --
    book_id
    --
    page_number
    --
    image_path
}
entity "book_tags" as bt {
    book_tags_id
    --
    book_id
    --
    tag_id
}
entity "tag" as t {
    tag_id
    --
    tag_name
}

b ||--|{ ab
ab }o--|| a
b ||--|{ p
b ||--o{ bt
bt }o--|| t

@enduml